openedx/openedx-filters

CHANGELOG.rst, setup.cfg
This PR adds missing configuration that changes init when calling bumpversion
=> fix: add missing configuration for bumpversion

setup.cfg
This PR adds configuration for tag generation using bumpversion
=> fix: missing tag configuration for bumpversion

openedx_filters/pipeline.py, openedx_filters/tests/test_exceptions.py, openedx_filters/tests/test_pipeline.py, openedx_filters/tests/test_utils.py
This PR changes relative imports to absolute to match openedx-events
=> refactor: change relative imports to absolute to match openedx-events

README.rst
This PR updates the readme file with repository info.
=> docs: update readme with repository info

openedx_filters/tooling.py
This PR fixes dictionary mishandling.
=> fix: copy dictionary before modifications

CHANGELOG.rst, openedx_filters/learning/filters.py
This PR adds relevant arguments for the certificate creation filter. Please, refer to this [PR](https://github.com/openedx/edx-platform/pull/29949) for more context.
Please, follow the instructions explained [here](https://github.com/openedx/edx-platform/pull/29949).
**Reviewers:**
finished.
=> refactor: add more relevant arguments to certificate creation filter

openedx_filters/learning/tests/test_filters.py, openedx_filters/tests/test_exceptions.py, openedx_filters/tests/test_filters.py, openedx_filters/tests/test_tooling.py
Add tests cases to improve coverage, so #31 and future build passes.
=> test: add tests cases to improve coverage

CHANGELOG.rst, openedx_filters/learning/filters.py, openedx_filters/learning/tests/test_filters.py, openedx_filters/tests/test_tooling.py
This PR:
* Remove CourseHomeRenderStarted since it's not going to be used
* Change RenderAlternativeCertificate to RenderAlternativeInvalidCertificate
=> refactor!: refactor due to integration feedback

openedx.yaml
Update release metadata ahead of the Olive release.
=> build: this repo is not branched for Open edX releases

catalog-info.yaml
**Description:** Adding the catalog-info.yaml to add this repo to backstage
**Dependencies:** none
**Merge deadline:** sooner rather than later
**Context:** this was an[ action item ](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3545171041/2022-09-28+Meeting+notes)from the architecture coordination wg
**Reviewers:**
**Author concerns:** None
=> build: Add structured maintainers information

.github/workflows/commitlint.yml
This PR adds a new workflow to check that commits comply with our standards when opening a PR.
**GH ISSUE:**
None
**Dependencies:**
None
ASAP
None.
Check the workflow execution.
**Reviewers:**
finished.
**Author concerns:** 
None for now.
=> ci: add commitlint GitHub workflow for pull requests

CHANGELOG.rst, openedx_filters/__init__.py, setup.cfg
This PR updates the library version to 1.x.x according to semantic standards to acknowledge its usage in production environments.
None 
ASAP
Documentation update.
Documentation update.
**Reviewers:**
finished.
**Author concerns:** 
None for now.
=> docs: Bump version to 1.x to acknowledge that this is in use in prod

README.rst
This PR updates documentation so it follows the latest practices in Open edX maintenance: https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055/decisions/0003-readme-specification.html
=> docs: Update README.rst with latest specifications

CHANGELOG.rst, openedx_filters/__init__.py, setup.py
This PR updates the Python classifiers in the lib setup file.
=> docs: update python classifiers in setup file

.github/workflows/ci.yml
This PR updates codecov to the latest release which use tokens per repository.
=> build: update codecov action to latest version with repo-specific tokens

docs/reference/index.rst, docs/reference/real-life-use-cases.rst
This PR adds a list of community use cases based on the results of GraphQL queries and GH searches. You can review the result here: https://docsopenedxorg--228.org.readthedocs.build/projects/openedx-filters/en/228/reference/real-life-use-cases.html
=> docs: [FC-0074] add real life use cases based on community adoption

docs/concepts/openedx-filters.rst, docs/conf.py, docs/index.rst
This PR references the main framework documentation in an effort to implement DRY docs.
=> docs: [FC-0074] reference main hooks docs to maintain DRY docs

docs/how-tos/create-a-new-filter.rst, docs/reference/index.rst, docs/reference/naming-suggestions.rst
This PR adds naming suggestions for implementing new Open edX Filters.
You can see the docs rendered here: 
"None" if there's no rush, or provide a specific date or event (and reason) if there is one.
finished.
=> docs: [FC-0074] add naming suggestions to use when creating new filters

changelog.d/20250401_114730_bryann.valderrama_add_config_formats_docs.rst, docs/decisions/0002-hooks-filter-config-location.rst, docs/reference/filters-configuration.rst
This PR updates the filter configuration docs to add a more detailed description of all filter configuration formats.
- https://github.com/openedx/openedx-filters/issues/181 (Currently, both single and multi-step pipelines are supported. Then, only updating the documentation is needed in this case)
See the updated documentation [here](https://docsopenedxorg--279.org.readthedocs.build/projects/openedx-filters/en/279/reference/filters-configuration.html).
None
=> docs: update filters configuration docs

docs/reference/django-plugins-and-filters.rst, openedx_filters/filters.py
Small docs update to make it clear the differences between testing and production behavior for operators/developers.
=> docs: Add some clarification on using filters with plugins.
