docs/index.rst
manage.py
test_utils/test_settings.py
tests/test_openedx_filters.py
tox.ini

This PR adds the necessary configuration to run unittesting using django settings.
1. PR #1 uses this configuration to run tests
**Reviewers:**

test: add missing configuration for testing

---

docs/decisions/0001-purpose-of-this-repo.rst
docs/decisions/0002-hooks-filter-config-location.rst
docs/decisions/0003-hooks-filter-tooling-pipeline.rst
docs/index.rst

This PRs adds Architectural Decision Records (ADR) for filters on the following subjects:
- Purpose of openedx-filters
- Tooling: how to execute filters
- Configuration: how to configure filters
**JIRA:** Link to JIRA ticket
**Dependencies:** dependencies on other outstanding PRs, issues, etc. 
**Merge deadline:** List merge deadline (if any)
**Installation instructions:** List any non-trivial installation 
instructions.
This PR just adds documentation. 
**Reviewers:**
finished.

docs: add ADRs for filter tooling and configuration

---

openedx_filters/__init__.py
openedx_filters/exceptions.py
openedx_filters/pipeline.py
openedx_filters/tests/__init__.py
openedx_filters/tests/test_exceptions.py
openedx_filters/tests/test_pipeline.py
openedx_filters/tests/test_utils.py
openedx_filters/utils.py
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.in
requirements/test.txt

This PR adds the tooling needed by the Hooks Extension Framework to execute filters. This project is described in more depth in the [OEP-50](https://github.com/edx/open-edx-proposals/pull/184).  
The tooling consists of a pipeline ([Pipeline tooling ADR](https://github.com/eduNEXT/openedx-filters/blob/ef4e5e093fb753539cd16729bc8f924ba964e7a5/docs/decisions/0003-hooks-filter-tooling-pipeline.rst)) that executes a list of functions pre-configured that are associated with the filter via Django settings ([Filters configuration ADR](https://github.com/eduNEXT/openedx-filters/blob/ef4e5e093fb753539cd16729bc8f924ba964e7a5/docs/decisions/0002-hooks-filter-config-location.rst)).
The architectural design records where the configuration and pipeline design used …

feat: add Hooks Extension Framework tooling for filters #2

---

CHANGELOG.rst
tox.ini

This PR adds support for 120 max doc lines. Suggestion taken from: https://github.com/eduNEXT/openedx-events/pull/18#discussion_r675183610

docs: changed max-doc-length due to community recommendation

---

docs/decisions/0002-hooks-filter-config-location.rst
openedx_filters/pipeline.py
openedx_filters/tests/__init__.py
openedx_filters/tests/test_pipeline.py
openedx_filters/tests/test_utils.py
openedx_filters/utils.py

This PR changes _hook_ to _filter_ and standardizes the configuration name.

fix: change variables names to match repository purpose

---

openedx_filters/exceptions.py
openedx_filters/pipeline.py
openedx_filters/tests/test_exceptions.py
openedx_filters/tests/test_pipeline.py
openedx_filters/utils.py

This PR renames HookFilterException to OpenEdxFilterException to be similar to [OpenEdxEventsException](https://github.com/eduNEXT/openedx-events/blob/71e82fcf0239537eab9c8740d464ffcb113bb111/openedx_events/exceptions.py#L6)
**JIRA:** 
Part of repository refactor: https://edunext.atlassian.net/browse/PS2021-914?atlOrigin=eyJpIjoiYWVmODliMjAzNWMyNDM3NzlhNTY2NDVlZDcxMTE1NDciLCJwIjoiaiJ9

refactor: change base exception name to OpenEdxFilterException

---

CHANGELOG.rst
docs/decisions/0003-hooks-filter-tooling-pipeline.rst
docs/decisions/0004-filters-naming-and-versioning.rst
docs/decisions/0005-filters-payload.rst
docs/decisions/0006-filter-debug-tooling.rst

This PR adds an Architectural Design Record for:
- Filters naming and versioning
- Filters payloads
- Debugging tools
Discuss [thread](https://discuss.openedx.org/t/hooks-framework-filters/5753) that goes along this conversation.
**Author concerns:**

docs: ADR for Open edX filters naming

---

openedx_filters/exceptions.py

**Description**
This PR changes the string representation for filters exceptions.
Before
```
File "/edx/src/openedx-filters/openedx_filters/tooling.py", line 211, in run_pipeline
result = step_runner.run(**accumulated_output)
File "/edx/src/openedx-filters-test-plugin/openedx_filters_test_plugin/pipeline.py", line 146, in run
raise PreLoginFilter.PreventLogin("You can't login on this site.")
openedx_filters.learning.auth.PreLoginFilter.PreventLogin: OpenEdxFilterException: You can't login on this site.
```
After
```
File "/edx/src/openedx-filters/openedx_filters/tooling.py", line 211, in run_pipeline
result = step_runner.run(**accumulated_output)
File "/edx/src/openedx-filters-test-plugin/openedx_filters_test_plugin/pipeline.py", line 146, in run
raise PreLoginFilter.PreventLogin("You …
```

fix: remove "OpenEdxFilterException:" from exception str repr

---

CHANGELOG.rst
openedx_filters/tests/test_tooling.py
openedx_filters/tooling.py

This PR changes `run` runner to `run_filter` according to the new steps definitions.

fix: use run_filter instead of run

---

CHANGELOG.rst
openedx_filters/tests/test_tooling.py
openedx_filters/tooling.py

This PR adds `fail_silently` when importing pipeline steps when running a filter pipeline.
1. Use these settings without installing the `openedx_filters_samples.samples` 
```
OPEN_EDX_FILTERS_CONFIG = {
"org.openedx.learning.student.login.requested.v1": {
"fail_silently": False,
"pipeline": [
"openedx_filters_samples.samples.pipeline.ModifyUserProfileBeforeLogin",
"openedx_filters_samples.samples.pipeline.StopLogin"
]
},
}
```
2. Then, login. The application should crash. 
3. Change `fail_silently` to `True`. Login again, the application should continue its execution as usual.
finished.

refactor: add fail_silently flag when importing pipeline steps

---

CHANGELOG.rst
openedx_filters/learning/filters.py

This PR adds:
- CourseUnenrollmentStarted: intended to be executed before the un-enrollment process starts.
- CertificateCreationRequested: intended to be executed before the certificate creation process starts.
- CertificateRenderStarted: intended to be executed before the certificate template rendering process starts.
- CohortChangeRequested: intended to be executed before the cohort change process starts.
- CourseAboutRenderStarted:  intended to be executed before course about template render starts.
- CourseHomeRenderStarted: intended to be executed before course home template render starts.
- DashboardRenderStarted: intended to be executed before the student's dashboard render starts.
Used by edx-platform.
Follow instructions in [PR …

 feat: add 2nd batch of filters

---

openedx_filters/learning/tests/__init__.py
openedx_filters/learning/tests/test_filters.py

This PR adds test suites for each filter definition implemented so far.
Run `make test-all`
**Reviewers:**

test: add test cases for each filter definition

---

CHANGELOG.rst
openedx_filters/learning/filters.py
openedx_filters/learning/tests/test_filters.py

**Description:** this PR change naming of some exceptions to avoid confusion with rendering valid/invalid templates. This addresses [this](https://github.com/openedx/edx-platform/pull/29994#discussion_r848065064) comment in filters PRs.

refactor: change dashboard/course about exceptions naming for clarity

---

CHANGELOG.rst
openedx_filters/__init__.py
openedx_filters/learning/filters.py
openedx_filters/learning/tests/test_filters.py

This adds the `VerticalBlockChildRenderStarted` filter which passes the child XBlock and it's rendering context dictionary to the filter allowing the filter pipeline to react to the content of the XBlock based on the context.
This is a follow up of the PoC implemented in PR  #35. The filter attempted in the previous PR was poorly placed and was limiting. The filter introduced in this PR provides a better opportunity for plugin's to enhance the experience based on the XBlock being rendered.
The Edit Links PR https://github.com/open-craft/openedx-edit-links/pull/1 shows one such use-case of adding extra HTML to the content of HTML Block before rendering.
**JIRA:** Link to JIRA ticket
**Dependencies:**
- https://github.com/openedx/edx-platform/pull/30773
**Merge deadline:** …

feat: adds the VerticalBlockChildRenderStarted filter

---

CHANGELOG.rst
README.rst

This PR updates the README file according to latest standards, including OEP-55.
ASAP
Just documentation.
Just documentation.
**Reviewers:**
finished.
**Author concerns:** 
how do we set readthedocs documentation?

docs: update documentation according latest standards

---

.github/workflows/upgrade-python-requirements.yml

This PR adds a github action which opens a PR updating python requirements in a weekly manner tagging the hooks-extension-framework team as reviewers.
Reference: https://github.com/openedx/openedx-events/pull/106
**Github issue**
https://github.com/openedx/openedx-filters/issues/40
As soon as possible.
**Reviewers:**
finished.

build: add upgrade python requirements bot

---

openedx_filters/learning/filters.py
openedx_filters/learning/tests/test_filters.py

This adds the ``CourseEnrollmentSiteFilterRequested`` filter which receive a Query Set context with enrollments information to allowing the filter pipeline to return the information that we need to filter.
An example of use is in [eox-tenant](https://github.com/eduNEXT/eox-tenant) custom filter step [pipeline](https://github.com/eduNEXT/eox-tenant/blob/master/eox_tenant/filters/pipeline.py), where it takes the enrollments information and is filtered by tenant request, returning only the enrollments in the current site for the user.
**JIRA:** N/A
**Dependencies:**
- https://github.com/openedx/edx-platform/pull/31331
**Merge deadline:** N/A
Be sure to use ``edx-platform`` branch with changes https://github.com/openedx/edx-platform/pull/31331 …

feat: adds the CourseEnrollmentSiteFilterRequested filter

---

.github/workflows/ci.yml
.github/workflows/pypi-publish.yml

This PR updates the current action versions to their latest. This issue might fix this kind of failures: https://github.com/openedx/openedx-filters/actions/runs/4195061648/jobs/7275542215
None
ASAP. We need to merge the other PR or at least find out if this works.
None
PR with successful checks
**Reviewers:**
finished.
**Author concerns:** 
Something breaking for the upgrades.

build: update github actions to latest versions

---

CHANGELOG.rst
openedx_filters/__init__.py
openedx_filters/learning/filters.py
openedx_filters/learning/tests/test_filters.py
setup.cfg

This adds `VerticalBlockRenderCompleted` filter that will be passed the rendered fragment of a vertical block, along with the context and the view in which it was rendered. 
This will allow for changing the rendered content by the pipeline steps. 
**JIRA:** NA
- https://github.com/openedx/edx-platform/pull/31388
**Merge deadline:**  None
**Installation instructions:** Nothing special
Detailed testing instructions with a sample pipeline step are available in the edx-paltform PR: https://github.com/openedx/edx-platform/pull/31388
**Reviewers:**
finished.
**Author concerns:**
Nothing comes to mind.

feat: adds VerticalBlockRenderCompleted filter

---

CHANGELOG.rst
openedx_filters/__init__.py
openedx_filters/learning/filters.py
openedx_filters/learning/tests/test_filters.py
setup.cfg

**Description:** This PR is to add one filter:
`AccountSettingsRenderStarted` filter which passes the account settings context before is  rendered.
**JIRA:** 
No direct openedx related ticket is available. Related tickets that add context to this change are:
- [DS-303](https://edunext.atlassian.net/browse/DS-303)
- https://github.com/openedx/edx-platform/pull/31295 Hook PR in edx-platform.
**Merge deadline:** List merge deadline (if any)
**Installation instructions:** List any non-trivial installation 
instructions.
The example application using this filter is implemented in [edunext-platoform](https://github.com/eduNEXT/edunext-platform/pull/691) and its PR contains the testing instructions.
**Reviewers:** …

feat: add filter before user setttings context is rendered

---

requirements/ci.in
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt

This PR removes the codecov pypi package which was deprecaded according to its the codevo.io page: https://about.codecov.io/blog/message-regarding-the-pypi-package/ 
**ISSUE:** 
https://discuss.openedx.org/t/codecov-python-package-removal/9817
None
ASAP so new PRs don't fail
Requirements files upgrade only
Requirements files upgrade only
**Reviewers:**
finished.
**Author concerns:**
codecov replacement 🤔, for more info about the current work of the replacement check: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3730931713/2023-04-14+Maintainer+s+Office+Hours+Notes

fix: remove deprecated codecov package to avoid failures

---

.github/dependabot.yml

**Description:** This PR adds a .github/dependabot.yml file to bring the repo up to day with the maintainers program
**Dependencies:** None
**Merge deadline:** None, but hopefully soon
**Installation instructions:** None, it's all done by github
Not easy to test. Must wait until dependabot actually opens a PR updating the actions.
See: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
**Reviewers:**
finished.
**Author concerns:** Do we need to add this, or by having it in https://github.com/openedx/.github/blob/master/.github/dependabot.yml it is already running?

Adding dependabot as part of the maintainers protocol

---

CHANGELOG.rst
openedx_filters/__init__.py
openedx_filters/learning/filters.py
openedx_filters/learning/tests/test_filters.py

**Description:** This PR adds a filter for modifying the [course home url](https://github.com/openedx/edx-platform/blob/aa7370c773dcd96850fbda8e4f6ad40950c10547/openedx/features/course_experience/__init__.py#L100) for externally hosted courses
**Reference**
The URL will flow downstream to both the B2B and B2C learner dashboards. B2B enterprise-course-enrollments API gets the course_home_url via another B2C helper function get_course_run_url in edx-platform ([source](https://github.com/openedx/edx-platform/blob/ba8a3c130db5936bf0851b8db261b6c7499968e0/lms/djangoapps/course_api/api.py#L281-L293)) whereas the B2C learner home init API calls course_home_url directly ([source](https://github.com/openedx/edx-platform/blob/ba8a3c130db5936bf0851b8db261b6c7499968e0/lms/djangoapps/learner_home/seria …

feat: Added a filter for modifying the course home url for externally hosted courses

---

README.rst

The current link 404s, as this repo's docs are empty
and unpublished.

docs: change docs link to edx-platform Hooks guide

---

CHANGELOG.rst
openedx_filters/__init__.py
openedx_filters/learning/filters.py
openedx_filters/learning/tests/test_filters.py

This PR adds a new filter to modify the instructor dashboard rendering process. For example: modify the section tabs of the instructor context --that specifies which tabs to render, adding a brand new one defined in a different plugin. The use case we're currently testing is to add a new tab to the instructor dashboard, which renders management information about an Xblock.
In case you want to test the use case shown here, you'll need a couple of stuff:
1. Install the LimeSurvey Xblock in the LMS/CMS services: `git+https://github.com/eduNEXT/xblock-limesurvey.git@MJG/instructor-tab`
2. Install this branch in the LMS/CMS services: `git+https://github.com/openedx/openedx-filters.git@MJG/instructor-tab-filters`
3. Change your edx-platform …

feat: add filter design to modify the instructor dashboard render

---

.readthedocs.yaml
requirements/dev.in
requirements/dev.txt
tox.ini

- Updated tox config to add tox 4.0 support
- Removed usage of tox-battery from requirements
- Updated `.readthedocs.yml` config file to fix the failing docs build check.

fix: add tox 4.0 support

---

CHANGELOG.rst
openedx_filters/__init__.py
openedx_filters/learning/filters.py
openedx_filters/learning/tests/test_filters.py

This PR adds a filter to modify the default template of submissions in an ORA assignment.
- New filter: `ORASubmissionViewRenderStarted`
- New exception: `RenderInvalidTemplate` 
These changes are based on those proposed in the [following ADR](https://github.com/openedx/edx-ora2/pull/2182)

feat: add ORA filter for submission view rendering intervention

---

CHANGELOG.rst
openedx_filters/__init__.py
openedx_filters/learning/filters.py
openedx_filters/learning/tests/test_filters.py

**Description:** Add a filter just before rendering of an XBlock scope. [See discussion forum](https://discuss.openedx.org/t/filter-in-xblock-render-pipeline/13095/5).
**Justification:** Some of our current work requires an ability to read and modify data in the XBlock render pipeline. While there *already* exist filters in the Vertical rendering pipeline, these are limited compared to the XBlock rendering pipeline in 2 important ways.
1. The vertical render does not have access to the original request object, meaning if we are otherwise unable to read/modify data on or in response to that request.
2. The vertical render pipeline does not apply to XBlock scopes outside of vertical/unit. If, for example, we ask to render an individual block, these filters will not get activated.
**JIRA:** …

feat: add filter for hooking XBlock Render

---

CHANGELOG.rst
docs/conf.py
docs/reference/filters.rst
docs/reference/index.rst

This PR adds the necessary configuration for automatic docs generation based on Open edX Filters classes, you can see the docs generated here: https://docsopenedxorg--173.org.readthedocs.build/projects/openedx-filters/en/173/

docs: add configuration for automatic filters docs generation

---

CHANGELOG.rst
openedx_filters/__init__.py
openedx_filters/learning/filters.py
openedx_filters/learning/tests/test_filters.py

**Description:** The purpose of this PR is to add an Open edX filter hook for getting the URL to the IDV page to the [GitHub - openedx/openedx-filters: Open edX filters from the Hooks Extensions Framework](https://github.com/openedx/openedx-filters)  repository.
For the sake of justifying this filter, here is the relevant [Open edX Product Proposal](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/4307386369/Proposal+Add+Extensibility+Mechanisms+to+IDV+to+Enable+Integration+of+New+IDV+Vendor+Persona) and [Issue](https://github.com/openedx/platform-roadmap/issues/367) to `Add Extensibility Mechanisms to IDV to Enable Integration of New IDV Vendor Persona`.
**JIRA:** [Link to JIRA ticket
](https://2u-internal.atlassian.net/browse/COSMO-423)
**Dependencies:** None
**Merge deadline:** N/A …

feat: Implement IDV URL Filters

---

.github/workflows/ci.yml
.github/workflows/pypi-publish.yml
.readthedocs.yaml
requirements/constraints.txt
setup.py
tox.ini

Addresses https://github.com/openedx/openedx-filters/issues/206 by dropping ubuntu-20.04 and partially addresses by dropping py3.8 https://github.com/openedx/openedx-filters/issues/212 in workflows

build: run workflows exclusively with ubuntu-latest and py11

---

CHANGELOG.rst
openedx_filters/__init__.py
openedx_filters/course_authoring/__init__.py
openedx_filters/course_authoring/filters.py
openedx_filters/course_authoring/tests/__init__.py
openedx_filters/course_authoring/tests/test_filters.py
openedx_filters/learning/filters.py
openedx_filters/learning/tests/test_filters.py

**Description:** Describe in a couple of sentences what this PR adds
This adds the TenantAwareLinkRenderStarted filter which receive a string context with LMS url to allowing the filter pipeline to return the information that we need to filter, in this case a tenant aware link from Studio to LMS.
An example of use is in [eox-tenant](https://github.com/eduNEXT/eox-tenant) custom filter step [pipeline](https://github.com/eduNEXT/eox-tenant/blob/master/eox_tenant/filters/pipeline.py), where it takes the LMS_ROOT_URL and return only the tenant aware link in the respective site.
**JIRA:** [DS-1003](https://edunext.atlassian.net/browse/DS-1003)
https://github.com/openedx/edx-platform/pull/35142
**Merge deadline:** N/A
Be sure to use …

feat: adds CourseAboutPageURLRequested and LMSPageURLRequested filters

---

CHANGELOG.rst
docs/reference/real-life-use-cases.rst
openedx_filters/__init__.py
openedx_filters/learning/filters.py
openedx_filters/learning/tests/test_filters.py

**Description:** This PR adds a filter to modify the default schedule queryset of the [automatic email messages](https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/manage_live_course/automatic_email.html) in `edx-platform`.
The filter receives a single `schedules` argument of type `QuerySet`. An example of use is in this [NAU pipeline](https://github.com/fccn/nau-openedx-extensions/pull/56) that allows filtering the Schedules to only send emails to users who have the option to receive emails enabled in their profile (`allow_newsletter=True`)
**JIRA:** N/A
**Dependencies:**
- https://github.com/openedx/edx-platform/pull/35982
**Merge deadline:** NO
**Installation instructions:**
1. Create a Tutor environment.
2. Install this plugin with the changes in this PR. :warning: …

feat: add schedule queryset requested filter

---

openedx_filters/course_authoring/filters.py
openedx_filters/learning/filters.py
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.txt

This PR modifies the docstrings of all current filters by adding:
- Better descriptions of their purpose.
- Typing hints.
- Filter type embedded in the docstring to be reflected in the docs generated by RTD.
- Trigger information to locate the filter in the corresponding services.
This PR addresses a concern raised by this PR removing hooks docs from edx-platform: https://github.com/openedx/edx-platform/pull/35921#issue-2690350343, where the table referencing where each event was triggered from was dropped.
You can review the changes here: https://docsopenedxorg--246.org.readthedocs.build/projects/openedx-filters/en/246/reference/filters.html
None
finished.

docs: [FC-0074] enrich docstrings following a template with more details

---

docs/concepts/openedx-filters.rst
docs/conf.py
docs/reference/filters-tooling.rst
docs/reference/index.rst
openedx_filters/course_authoring/filters.py
openedx_filters/filters.py
openedx_filters/learning/filters.py
openedx_filters/tooling.py

This PR includes references to filter tooling, making it easier for developers to find it while reading the documentation.
You can see the rendered docs here: https://docsopenedxorg--253.org.readthedocs.build/projects/openedx-filters/en/253/reference/filters-tooling.html
None
finished.

docs: [FC-0074] include tooling in references

---

Makefile
mypy.ini
openedx_filters/course_authoring/filters.py
openedx_filters/exceptions.py
openedx_filters/learning/filters.py
openedx_filters/learning/tests/test_filters.py
openedx_filters/tests/test_tooling.py
openedx_filters/tooling.py
openedx_filters/utils.py
requirements/dev.txt
requirements/doc.txt
requirements/quality.in
requirements/quality.txt
requirements/test.in
requirements/test.txt

This PR supports mypy based on what's already implemented for the filter tooling. The aim is to gradually start refactoring the library so it's more type-aware by starting to type what's currently here without any modifications to the codebase, mainly changing method signatures.
⚠️ Properly supporting mypy in this repo might need more adjustments and reactors so all types make sense, but this is a starting point for developers to start using type hints and understanding what their filters signatures return.
You can run `tox -e quality` or review the workflow run here: https://github.com/openedx/openedx-filters/actions/runs/13133404193/job/36643330405?pr=250#step:6:29
"None" if there's no rush, or provide a specific date or event (and reason) if there is one.
Check off if complete *or* not …

feat: [FC-0074] add static type checking for documentation purposes

---

CHANGELOG.rst
docs/common_refs.rst
docs/concepts/openedx-filters.rst
docs/conf.py
docs/how-tos/create-a-new-filter.rst
docs/how-tos/create-a-pipeline-step.rst
docs/reference/django-plugins-and-filters.rst
openedx_filters/__init__.py

This PR adds the [linkcode Sphinx extension](https://www.sphinx-doc.org/en/master/usage/extensions/linkcode.html) to include the source code in the classes, functions, and methods in the documentation.
You can check the updated documentation in the checks of this PR.
N/A
N/A
finished.

docs: add linkcode extension

---

docs/concepts/openedx-filters.rst

docs: Update edx.rtd links to docs.openedx.org

---

Makefile
requirements/dev.txt
requirements/doc.txt
requirements/quality.in
requirements/quality.txt
ruff.toml
tox.ini

This PR replaces the [`pydocstyle`](https://github.com/PyCQA/pydocstyle) deprecated library with [`ruff`](https://docs.astral.sh/ruff/).
It's important to note that **ruff** can replace other packages such as `pylint`, `pycodestyle`, and `isort`. This is just the initial step to fully implement a faster and modern tool.
You can run `make quality` in your local or see the PR checks.
None
finished.

feat: replace `pydocstyle` with `ruff`

---

CHANGELOG.rst
changelog.d/20250225_124832_bryann.valderrama_scriv.rst
changelog.d/20250326_102750_bryann.valderrama_add_changelog_entries.rst
changelog.d/20250326_103610_bryann.valderrama_add_changelog_entries.rst
changelog.d/20250326_104004_bryann.valderrama_add_changelog_entries.rst
changelog.d/20250326_104238_bryann.valderrama_add_changelog_entries.rst
changelog.d/20250326_110813_bryann.valderrama_add_changelog_entries.rst
changelog.d/20250326_111322_bryann.valderrama_add_changelog_entries.rst
changelog.d/20250326_111517_bryann.valderrama_add_changelog_entries.rst

This PR adds the changelog entries for the new release using `scriv`.
- https://github.com/openedx/openedx-filters/pull/268#pullrequestreview-2699282533
None

chore: add changelog entries for new release

---

README.rst

This PR fixes the Python CI status badge in the README. The badge was generated in **Actions > Python CI > [•••] > Create status badge**
None

chore: fix python ci status badge

---

catalog-info.yaml

This PR updates the code owners in backstage from the old naming convention to the new one.
This issue was raised by Sarina here: https://github.com/openedx/openedx-filters/issues/310
I'm requesting a review from the members of the new group, from which I'm also part.
None, as this won't require a release. It is for backstage primarily.

chore: changing owner group in catalog-info.yaml
